# docker-compose.yml
version: '3.7'
services:
  app:
    container_name: online-store-api
    build: .
    depends_on:
      - database
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
    networks:
      - online-store

  database:
    container_name: online-store-database
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./.env
    networks:
      - online-store

networks:
  online-store:
    driver: bridge